version: "2"
services:
        weba:
            build: docker/web
            links:
                - db:db
                - redis
            expose:
                - 80

        webb:
            build: docker/web
            links:
                - db
                - redis
            expose:
                - 80

        webc:
            build: docker/web
            links:
                - db
                - redis
            expose:
                - 80

        db:
            build: docker/db
            environment: 
                MYSQL_ROOT_PASSWORD: secret
                MYSQL_DB: webuser
                MYSQL_USER: dbadmin
                MYSQL_PASS: dbpassword
                MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            ports:
                - 3306:3306
        redis:
            image: redis
            ports:
                - "6379"

        haproxy:
            build: docker/haproxy
            links:
                - weba
                - webb
                - webc
            ports:
                - "80:80"
                - "70:70"
            expose:
                - "80"
                - "70"
