version: "2"


volumes: 
    haproxy_cfg:
        driver: local
    
services:
        web:
            build: docker/web
            environment:
                - DEPLOYMENT_ENV=test              
            links:
                - db:db
                - redis
            labels:
                - "com.example.description=test"
        db:
            build: docker/db
            environment: 
                MYSQL_ROOT_PASSWORD: secret
                MYSQL_DB: webuser
                MYSQL_USER: dbadmin
                MYSQL_PASS: dbpassword
                MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            ports:
                - 3306:3306
        redis:
            image: redis
            ports:
                - "6379"

        haproxy:
            build: docker/haproxy
            ports:
                - "80:80"
                - "70:70"
            depends_on:
                - haproxy-gen
            volumes: 
                - haproxy_cfg:/usr/local/etc/haproxy/
            expose:
                - "80"
                - "70"
            restart: "always"

        haproxy-gen:
            build: docker/docker-gen
            volumes: 
                - /var/run/docker.sock:/tmp/docker.sock:ro
                - haproxy_cfg:/usr/local/etc/haproxy
            environment: 
                - "BACKEND=web"
                - "BACKEND_PORT=80"
                - "SERVICE=haproxy"
                - "PROJECT=autoscalewebfarm"